DROP TABLE IF EXISTS orders09;
CREATE TABLE orders09 (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    amount      DECIMAL(10,2) NOT NULL,
    status      VARCHAR(16) NOT NULL,
    created_at  DATETIME    NOT NULL
);
INSERT INTO orders09 (user_id, amount, status, created_at)
SELECT FLOOR(RAND()*100000)+1,
       ROUND(RAND()*10000,2),
       ELT(FLOOR(RAND()*3)+1,'paid','pending','cancelled'),
       NOW() - INTERVAL FLOOR(RAND()*365) DAY
FROM
  (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3
   UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7
   UNION ALL SELECT 8 UNION ALL SELECT 9) a,
  (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3
   UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7
   UNION ALL SELECT 8 UNION ALL SELECT 9) b,
  (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3
   UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7
   UNION ALL SELECT 8 UNION ALL SELECT 9) c,
  (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3
   UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7
   UNION ALL SELECT 8 UNION ALL SELECT 9) d,
  (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3
   UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7
   UNION ALL SELECT 8 UNION ALL SELECT 9) e,
  (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3
   UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7
   UNION ALL SELECT 8 UNION ALL SELECT 9) f;
SELECT COUNT(*) AS total_rows FROM orders09;
